// ══════════════════════════════════════════════
// CombinatorialPurgedCV — acceptance vs skfolio + leakage invariants
// ══════════════════════════════════════════════
//
// Two layers of evidence:
//
// 1. ACCEPTANCE: the three doctests from skfolio's _combinatorial.py
//    (CombinatorialPurgedCV docstring, lines ~104/122/140) transcribed
//    verbatim, plus values generated by running skfolio's numpy split /
//    get_path_ids logic verbatim (stripped of plotly/pandas) as an oracle.
//    A subtly-wrong CV produces false conclusions that LOOK rigorous — if
//    any of these fail after touching cpcv.ts, the port has diverged from
//    the reference: stop and re-derive, do not "fix" the expected values.
//
// 2. INVARIANTS: train ∩ test = ∅ (the whole reason this module exists),
//    every path uses every fold exactly once, parameter validation.

import { describe, test, expect } from "bun:test";
import { CombinatorialPurgedCV } from "./cpcv";

describe("CombinatorialPurgedCV — skfolio doctest acceptance", () => {
  // >>> cv = CombinatorialPurgedCV(n_folds=3, n_test_folds=2)  # X: 12 obs
  test("doctest 1: n_folds=3, n_test_folds=2, no purge/embargo", () => {
    const cv = new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2 });
    const splits = cv.split(12);
    expect(splits.length).toBe(3);
    expect(splits[0].trainIndex).toEqual([8, 9, 10, 11]);
    expect(splits[0].testIndexList).toEqual([
      [0, 1, 2, 3],
      [4, 5, 6, 7],
    ]);
    expect(splits[1].trainIndex).toEqual([4, 5, 6, 7]);
    expect(splits[1].testIndexList).toEqual([
      [0, 1, 2, 3],
      [8, 9, 10, 11],
    ]);
    expect(splits[2].trainIndex).toEqual([0, 1, 2, 3]);
    expect(splits[2].testIndexList).toEqual([
      [4, 5, 6, 7],
      [8, 9, 10, 11],
    ]);
  });

  // >>> cv = CombinatorialPurgedCV(n_folds=3, n_test_folds=2, purged_size=1)
  test("doctest 2: purged_size=1 removes train obs on both sides of test blocks", () => {
    const cv = new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2, purgedSize: 1 });
    const splits = cv.split(12);
    // Split 0: test folds {0,1} are one contiguous block 0..7 → purge only 8
    expect(splits[0].trainIndex).toEqual([9, 10, 11]);
    // Split 1: test {0,2} → blocks 0..3 and 8..11 → purge 4 (after) and 7 (before)
    expect(splits[1].trainIndex).toEqual([5, 6]);
    // Split 2: test {1,2} → block 4..11 → purge 3 (before)
    expect(splits[2].trainIndex).toEqual([0, 1, 2]);
    // Test sets never shrink from purging
    expect(splits[1].testIndexList).toEqual([
      [0, 1, 2, 3],
      [8, 9, 10, 11],
    ]);
  });

  // >>> cv = CombinatorialPurgedCV(n_folds=3, n_test_folds=2, embargo_size=1)
  test("doctest 3: embargo_size=1 removes train obs only AFTER test blocks", () => {
    const cv = new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2, embargoSize: 1 });
    const splits = cv.split(12);
    expect(splits[0].trainIndex).toEqual([9, 10, 11]);
    expect(splits[1].trainIndex).toEqual([5, 6, 7]); // embargo eats 4, not 7
    expect(splits[2].trainIndex).toEqual([0, 1, 2, 3]); // nothing before a block is embargoed
  });

  test("path ids match skfolio get_path_ids() (oracle-generated)", () => {
    // Values from running skfolio's get_path_ids numpy code verbatim.
    expect(new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2 }).getPathIds()).toEqual([
      [0, 0],
      [1, 0],
      [1, 1],
    ]);
    expect(new CombinatorialPurgedCV({ nFolds: 4, nTestFolds: 3 }).getPathIds()).toEqual([
      [0, 0, 0],
      [1, 1, 0],
      [2, 1, 1],
      [2, 2, 2],
    ]);
    const big = new CombinatorialPurgedCV({ nFolds: 10, nTestFolds: 2 });
    expect(big.nSplits).toBe(45); // C(10,2)
    expect(big.nTestPaths).toBe(9); // 45·2/10
    const ids = big.getPathIds();
    expect(ids.slice(0, 6)).toEqual([
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
      [4, 0],
      [5, 0],
    ]);
    expect(ids.slice(42)).toEqual([
      [7, 7],
      [8, 7],
      [8, 8],
    ]);
  });

  test("10 folds / 2 test folds / purge=2 / embargo=1 on 120 obs (oracle-generated)", () => {
    const cv = new CombinatorialPurgedCV({
      nFolds: 10,
      nTestFolds: 2,
      purgedSize: 2,
      embargoSize: 1,
    });
    const splits = cv.split(120);
    expect(splits.length).toBe(45);
    // Split 0: test folds {0,1} = obs 0..23; purge+embargo remove 24,25,26.
    expect(splits[0].trainIndex[0]).toBe(27);
    expect(splits[0].trainIndex.length).toBe(93); // 120 − 24 test − 3 purged
    expect(splits[0].trainIndex[92]).toBe(119);
  });
});

describe("CombinatorialPurgedCV — leakage invariants", () => {
  const configs = [
    { nFolds: 3, nTestFolds: 2, purgedSize: 0, embargoSize: 0, n: 12 },
    { nFolds: 3, nTestFolds: 2, purgedSize: 1, embargoSize: 1, n: 12 },
    { nFolds: 5, nTestFolds: 2, purgedSize: 1, embargoSize: 1, n: 25 },
    { nFolds: 4, nTestFolds: 3, purgedSize: 1, embargoSize: 0, n: 20 }, // nTestFolds = nFolds−1
    { nFolds: 10, nTestFolds: 2, purgedSize: 2, embargoSize: 1, n: 121 }, // ragged length
    { nFolds: 6, nTestFolds: 3, purgedSize: 1, embargoSize: 2, n: 61 },
  ];

  test("train ∩ test = ∅ after purge and embargo, in every split of every config", () => {
    for (const c of configs) {
      const cv = new CombinatorialPurgedCV(c);
      for (const [i, s] of cv.split(c.n).entries()) {
        const train = new Set(s.trainIndex);
        for (const testFold of s.testIndexList) {
          for (const t of testFold) {
            if (train.has(t)) {
              throw new Error(
                `LEAKAGE: obs ${t} in both train and test, split ${i}, ${JSON.stringify(c)}`
              );
            }
          }
        }
      }
    }
  });

  test("every observation is either train, test, or purged — never lost from test", () => {
    // Test folds must always be complete contiguous folds covering all
    // observations across a path; purging shrinks only the TRAIN side.
    const cv = new CombinatorialPurgedCV({ nFolds: 5, nTestFolds: 2, purgedSize: 2, embargoSize: 1 });
    const splits = cv.split(50);
    const testSet = cv.testSetIndex;
    for (const [i, s] of splits.entries()) {
      for (const [j, fold] of s.testIndexList.entries()) {
        expect(fold.length).toBe(10); // full fold, never purged
        expect(fold[0]).toBe(testSet[i][j] * 10);
      }
    }
  });

  test("each path visits every fold exactly once (paths are full-length backtests)", () => {
    for (const { nFolds, nTestFolds } of [
      { nFolds: 3, nTestFolds: 2 },
      { nFolds: 10, nTestFolds: 2 },
      { nFolds: 6, nTestFolds: 4 },
      { nFolds: 4, nTestFolds: 3 },
    ]) {
      const cv = new CombinatorialPurgedCV({ nFolds, nTestFolds });
      const pathIds = cv.getPathIds();
      const testSet = cv.testSetIndex;
      // pathFolds[p] = folds covered by path p
      const pathFolds: number[][] = Array.from({ length: cv.nTestPaths }, () => []);
      pathIds.forEach((row, splitId) => {
        row.forEach((pathId, j) => pathFolds[pathId].push(testSet[splitId][j]));
      });
      for (const folds of pathFolds) {
        expect([...folds].sort((a, b) => a - b)).toEqual(
          Array.from({ length: nFolds }, (_, f) => f)
        );
      }
    }
  });
});

describe("CombinatorialPurgedCV — parameter validation and edge cases", () => {
  test("rejects invalid fold counts with clear messages", () => {
    expect(() => new CombinatorialPurgedCV({ nFolds: 2, nTestFolds: 2 })).toThrow(/at least 3/);
    expect(() => new CombinatorialPurgedCV({ nFolds: 5, nTestFolds: 1 })).toThrow(/at least 2/);
    expect(() => new CombinatorialPurgedCV({ nFolds: 5, nTestFolds: 5 })).toThrow(/greater than/);
    expect(() => new CombinatorialPurgedCV({ nFolds: 5, nTestFolds: 6 })).toThrow(/greater than/);
    expect(() => new CombinatorialPurgedCV({ nFolds: 3.5, nTestFolds: 2 })).toThrow(/integer/);
    expect(() => new CombinatorialPurgedCV({ purgedSize: -1 })).toThrow(/negative/);
    expect(() => new CombinatorialPurgedCV({ embargoSize: -1 })).toThrow(/negative/);
  });

  test("rejects purge+embargo that would eat a whole fold", () => {
    // fold size = 12/3 = 4 → purged+embargo must be < 3
    const eat = new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2, purgedSize: 2, embargoSize: 1 });
    expect(() => eat.split(12)).toThrow(/purgedSize \+ embargoSize/);
    // boundary: 2 is still allowed
    const ok = new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2, purgedSize: 1, embargoSize: 1 });
    expect(ok.split(12).length).toBe(3);
  });

  test("rejects series too short for the fold count", () => {
    const cv = new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2 });
    expect(() => cv.split(2)).toThrow(/nSamples/); // fewer samples than folds
    // 5 obs / 3 folds → fold size 1 → even purge 0 is rejected (matches reference)
    expect(() => cv.split(5)).toThrow(/purgedSize \+ embargoSize/);
  });

  test("rejects combinatorial blowups", () => {
    expect(() => new CombinatorialPurgedCV({ nFolds: 40, nTestFolds: 20 })).toThrow(/splits/);
  });

  test("ragged series: trailing remainder joins the last fold", () => {
    const cv = new CombinatorialPurgedCV({ nFolds: 3, nTestFolds: 2 });
    const splits = cv.split(14); // fold size 4, remainder 2 → last fold has 6
    expect(splits[2].testIndexList[1]).toEqual([8, 9, 10, 11, 12, 13]);
    // and the remainder is never silently dropped into every train set
    for (const s of splits) {
      const seen = new Set([...s.trainIndex, ...s.testIndexList.flat()]);
      expect(seen.size).toBeGreaterThanOrEqual(12); // only purged obs may be missing
    }
  });

  test("defaults match skfolio (nFolds=10, nTestFolds=8)", () => {
    const cv = new CombinatorialPurgedCV();
    expect(cv.nFolds).toBe(10);
    expect(cv.nTestFolds).toBe(8);
    expect(cv.nSplits).toBe(45); // C(10,8)
    expect(cv.nTestPaths).toBe(36); // 45·8/10
  });
});
